// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDOI(arg1) {
  return window['go']['main']['App']['AddDOI'](arg1);
}

export function ClearWorkspace() {
  return window['go']['main']['App']['ClearWorkspace']();
}

export function DeletePaper(arg1) {
  return window['go']['main']['App']['DeletePaper'](arg1);
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function DownloadBatchPDFs(arg1) {
  return window['go']['main']['App']['DownloadBatchPDFs'](arg1);
}

export function DownloadPDF(arg1) {
  return window['go']['main']['App']['DownloadPDF'](arg1);
}

export function ExportWorkspaceBibTeX() {
  return window['go']['main']['App']['ExportWorkspaceBibTeX']();
}

export function FetchFutureCitations(arg1, arg2) {
  return window['go']['main']['App']['FetchFutureCitations'](arg1, arg2);
}

export function FetchPastReferences(arg1, arg2) {
  return window['go']['main']['App']['FetchPastReferences'](arg1, arg2);
}

export function GenerateAPACitation(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GenerateAPACitation'](arg1, arg2, arg3, arg4);
}

export function GenerateBibTeX(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GenerateBibTeX'](arg1, arg2, arg3, arg4);
}

export function GenerateFormattedCitation(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GenerateFormattedCitation'](arg1, arg2, arg3, arg4, arg5);
}

export function GenerateRIS(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GenerateRIS'](arg1, arg2, arg3, arg4);
}

export function GetAllPapers() {
  return window['go']['main']['App']['GetAllPapers']();
}

export function GetFutureCitations(arg1) {
  return window['go']['main']['App']['GetFutureCitations'](arg1);
}

export function GetPastReferences(arg1) {
  return window['go']['main']['App']['GetPastReferences'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ImportFile(arg1) {
  return window['go']['main']['App']['ImportFile'](arg1);
}

export function OpenPDFFile(arg1) {
  return window['go']['main']['App']['OpenPDFFile'](arg1);
}

export function ReadClipboard() {
  return window['go']['main']['App']['ReadClipboard']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectAndImportFile() {
  return window['go']['main']['App']['SelectAndImportFile']();
}
