// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {settings} from '../models';

export function AddDOI(arg1:string):Promise<domain.Paper>;

export function ClearWorkspace():Promise<void>;

export function DeletePaper(arg1:string):Promise<void>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function DownloadBatchPDFs(arg1:Array<string>):Promise<Array<domain.DownloadResult>>;

export function DownloadPDF(arg1:string):Promise<domain.DownloadResult>;

export function ExportWorkspaceBibTeX():Promise<string>;

export function FetchFutureCitations(arg1:string,arg2:number):Promise<Array<domain.Paper>>;

export function FetchPastReferences(arg1:string,arg2:number):Promise<Array<domain.Paper>>;

export function GenerateAPACitation(arg1:string,arg2:string,arg3:string,arg4:number):Promise<string>;

export function GenerateBibTeX(arg1:string,arg2:string,arg3:string,arg4:number):Promise<string>;

export function GenerateFormattedCitation(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string):Promise<string>;

export function GenerateRIS(arg1:string,arg2:string,arg3:string,arg4:number):Promise<string>;

export function GetAllPapers():Promise<Array<domain.Paper>>;

export function GetFutureCitations(arg1:string):Promise<Array<domain.Paper>>;

export function GetPastReferences(arg1:string):Promise<Array<domain.Paper>>;

export function GetSettings():Promise<settings.AppSettings>;

export function ImportFile(arg1:string):Promise<Array<string>>;

export function OpenPDFFile(arg1:string):Promise<void>;

export function ReadClipboard():Promise<string>;

export function SaveSettings(arg1:settings.AppSettings):Promise<void>;

export function SelectAndImportFile():Promise<Array<string>>;
